try {
    throw "an error message thrown";
}
catch (err) {
    console.log(err);
}